name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  CI_job:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Install Python3
       uses: actions/setup-python@v2
       with:
        python-version: 3.9
      -name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -name: Successfull
        run: echo "Successfull"
